name: gymapp
description: "A simple flutter gym app for saving weights, number of reps and sets."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  material_design_icons_flutter: ^7.0.7296
  url_launcher: ^6.3.2
  riverpod_annotation: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.3
  build_runner: ^2.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - assets/logo/